name: Release Crystal

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v0.1.0, v1.0.0, etc.

jobs:
  release:
    runs-on: macos-latest
    
    permissions:
      contents: write  # Required for creating releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.15.1'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build main process
      run: pnpm run build:main

    - name: Rebuild native modules
      run: pnpm run electron:rebuild

    - name: Build and publish macOS application
      run: pnpm run release:mac
      env:
        # GitHub token for publishing release
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # macOS code signing certificate
        CSC_LINK: ${{ secrets.APPLE_CERTIFICATE }}
        CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        # macOS notarization credentials
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        # Enable automatic certificate discovery
        CSC_IDENTITY_AUTO_DISCOVERY: 'true'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: crystal-macos-${{ github.ref_name }}
        path: |
          dist-electron/*.dmg
          dist-electron/*.zip
          dist-electron/latest-mac.yml
        if-no-files-found: error
        retention-days: 90